# Generated by Django 3.1 on 2021-02-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='private',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
